### PR TITLE
ActorPath.For now also works with a class that implements IActorGrain as the type parameter

### PR DESCRIPTION
**Pull request by cjenp**
ActorPath.ActorPath For(Type @interface, string id) now check if the supplied type parameter is an interface, if not it finds the appropriate interface. I also added a test, might be a bit overkill for this change?

### CODE REVIEW

**Comment by cjenp** [comment]
I noticed there is allready a similar/identical method to the one i added: ActorGrain.InterfaceOf(Type type).
Maybe it would be better to use the existing one (it woul have to be moved to ActorPath probbably)?

**Comment by yevhen** [comment]
Ye, I'll move this helper to Orleankka core lib

**Comment by yevhen** [comment]
Thanks for PR!

**Comment by cjenp** [comment]
Thank you for the quick merge and release!

**Pull request merged**
